In [1]:
import numpy as np

In [3]:
#soal nomor 1
a = np.array([[23,50],
              [7,12]])

b = np.array([[57,67],
             [99,43]])
c = np.array([[75,21],
              [57,12]])
d = np.array([[87,26],
              [18,84]])

In [18]:
tensor = np.array([[a,b],[c,d]])
tensor

array([[[[23, 50],
         [ 7, 12]],

        [[57, 67],
         [99, 43]]],


       [[[75, 21],
         [57, 12]],

        [[87, 26],
         [18, 84]]]])

In [20]:
tensor[1,:,:,:]

array([[[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

-----

In [21]:
#soal kedua
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([17,22,19])
A , B

(array([[ 23,  50,  19],
        [  7,  12, 109],
        [ 57,  67,  98]]),
 array([17, 22, 19]))

In [22]:
A @ B
#hasilnya berupa 3x1

array([1852, 2454, 4305])

---

In [24]:
#soal ketiga, 
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [26]:
#transpose
np.transpose(A)

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [27]:
#determinan
np.linalg.det(A)

131344.0000000002

In [28]:
#inverse
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])