In [1]:
import numpy as np

In [8]:
matriks = np.array([[1,-1],
                    [6,4]])

a = np.array([1,3])

In [9]:
eig_val , eig_vec = np.linalg.eig(matriks)
eig_val,eig_vec

(array([2.5+1.93649167j, 2.5-1.93649167j]),
 array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
        [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]]))

In [10]:
a = np.array([1,3]) /np.sqrt(10)
a
#hasil a adalah eigen vector yang seharusnya dicocokkan dengan eigen vector pada array [[1,-1],[6,4]]

array([0.31622777, 0.9486833 ])

eigenvector di atas [0.316,0.948] tidak ada yang mirip dengan eigenvector dari matriks [[1,-1],[6,4]]

In [12]:
#dekomposisi ulang matriks menggunakan eigendecomposition
eig_decomposition = eig_vec @ np.diag(eig_val) @ np.linalg.inv(eig_vec)
eig_decomposition

array([[ 1.+4.4408921e-16j, -1.+0.0000000e+00j],
       [ 6.-4.4408921e-16j,  4.+0.0000000e+00j]])

dapat disimpulkan bahwa [1,3] bukan eigenvector dari [[1,1],[6,4]]